# Generated by Django 5.0.6 on 2024-05-23 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=100)),
                ('type_of_user', models.CharField(choices=[('seller', 'Seller'), ('buyer', 'Buyer')], max_length=10)),
            ],
        ),
    ]
