# Generated by Django 5.0.6 on 2024-05-23 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('my_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100)),
                ('square_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('BHK', models.IntegerField()),
                ('bathroom', models.IntegerField()),
                ('hospitals_nearby', models.CharField(max_length=100, null=True)),
                ('colleges_nearby', models.CharField(max_length=100, null=True)),
                ('photos', models.ImageField(null=True, upload_to='rentify_upload/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('furnishing', models.CharField(choices=[('fully-furnished', 'Fully Furnished'), ('semi-furnished', 'Semi Furnished'), ('unfurnished', 'Unfurnished')], max_length=20)),
                ('parking', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='my_users.myuser')),
            ],
        ),
    ]
